#!/usr/bin/env bash
#
# install.sh - Install the control panel into a Kubernetes cluster.
#
# This script:
#   1. Validates that kubectl is available and connected to a cluster.
#   2. Prompts interactively for the initial admin password.
#   3. Generates fresh AES_KEY and JWT_SECRET via openssl.
#   4. Renders a Secret (control-panel-secrets) into secret.yaml (git-ignored).
#   5. Applies all manifests in this directory to the cluster.
#   6. Prints the NodePort access URL.
#
# Idempotent: re-running regenerates the Secret. If a Secret already exists in
# the cluster you will be warned and asked to confirm overwriting it.
#
# Usage:
#   ./install.sh
#
# Prerequisites:
#   - kubectl installed and configured to talk to the target cluster.
#   - The control panel image built and pushed to the private registry:
#       docker build -t registry-xirang.jxslpt.cn:30443/tai-dev/control-panel:latest control_panel/backend
#       docker push registry-xirang.jxslpt.cn:30443/tai-dev/control-panel:latest
#     The cluster nodes must be able to pull from that registry (imagePullPolicy: Always).
#     See README.md for self-signed/insecure-registry handling.

set -euo pipefail

# --- constants -------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRET_FILE="${SCRIPT_DIR}/secret.yaml"
SECRET_NAME="control-panel-secrets"
NAMESPACE="control-panel"

# --- helpers ---------------------------------------------------------------

log() {
    printf '\033[1;34m[install]\033[0m %s\n' "$*"
}

warn() {
    printf '\033[1;33m[warn]\033[0m %s\n' "$*" >&2
}

die() {
    printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2
    exit 1
}

# --- preflight -------------------------------------------------------------

command -v kubectl >/dev/null 2>&1 || die "kubectl not found on PATH. Install kubectl and configure it to talk to your cluster."

if ! kubectl cluster-info >/dev/null 2>&1; then
    die "kubectl cannot reach the cluster. Check your kubeconfig / context."
fi

command -v openssl >/dev/null 2>&1 || die "openssl not found on PATH. Install openssl."

# --- generate secret values ------------------------------------------------

log "Generating AES_KEY (32 random bytes, base64)..."
AES_KEY="$(openssl rand 32 | base64 | tr -d '\n')"
if [ -z "${AES_KEY}" ]; then die "failed to generate AES_KEY"; fi

log "Generating JWT_SECRET (32 random bytes, base64)..."
JWT_SECRET="$(openssl rand 32 | base64 | tr -d '\n')"
if [ -z "${JWT_SECRET}" ]; then die "failed to generate JWT_SECRET"; fi

log "Prompt for initial admin password (input hidden)..."
while true; do
    read -r -s -p "  Initial admin password (min 8 chars): " ADMIN_PW
    echo
    if [ "${#ADMIN_PW}" -lt 8 ]; then
        warn "Password must be at least 8 characters. Please try again."
        continue
    fi
    read -r -s -p "  Confirm password: " ADMIN_PW_CONFIRM
    echo
    if [ "${ADMIN_PW}" != "${ADMIN_PW_CONFIRM}" ]; then
        warn "Passwords do not match. Please try again."
        continue
    fi
    break
done

ADMIN_INIT_PASSWORD_B64="$(printf '%s' "${ADMIN_PW}" | base64 | tr -d '\n')"
unset ADMIN_PW ADMIN_PW_CONFIRM

# --- warn on existing secret ----------------------------------------------

if kubectl get secret "${SECRET_NAME}" -n "${NAMESPACE}" >/dev/null 2>&1; then
    warn "Secret '${SECRET_NAME}' already exists in namespace '${NAMESPACE}'."
    warn "Re-applying will OVERWRITE the existing values, which will:"
    warn "  - Rotate AES_KEY: existing encrypted per-worker SSH private keys become DECRYPTABLE ONLY IF the old AES_KEY is preserved (they are not - this regenerates it)."
    warn "    Existing encrypted data will become unreadable. Back up the old AES_KEY first if you need to preserve it."
    warn "  - Rotate JWT_SECRET: all current login sessions are invalidated."
    warn "  - Reset ADMIN_INIT_PASSWORD: only takes effect if no admin has been seeded yet (the admin password is only seeded on first startup)."
    read -r -p "Overwrite? Type 'yes' to continue: " CONFIRM
    [ "${CONFIRM}" = "yes" ] || die "aborted by user."
fi

# --- render secret.yaml ----------------------------------------------------

log "Rendering ${SECRET_FILE}..."
cat > "${SECRET_FILE}" <<EOF
# Generated by install.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ').
# DO NOT COMMIT THIS FILE - it is git-ignored (see .gitignore).
apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: control-panel
type: Opaque
data:
  AES_KEY: ${AES_KEY}
  JWT_SECRET: ${JWT_SECRET}
  ADMIN_INIT_PASSWORD: ${ADMIN_INIT_PASSWORD_B64}
EOF
chmod 600 "${SECRET_FILE}" 2>/dev/null || true
unset AES_KEY JWT_SECRET ADMIN_INIT_PASSWORD_B64

# --- apply manifests -------------------------------------------------------

log "Applying manifests from ${SCRIPT_DIR}..."
kubectl apply -f "${SCRIPT_DIR}/rbac.yaml"
kubectl apply -f "${SCRIPT_DIR}/pvc.yaml"
kubectl apply -f "${SECRET_FILE}"
kubectl apply -f "${SCRIPT_DIR}/deployment.yaml"
kubectl apply -f "${SCRIPT_DIR}/service.yaml"

# --- print access info -----------------------------------------------------

log "Installation complete."
echo
echo "Control panel is deploying to namespace '${NAMESPACE}'."
echo
echo "Wait for the pod to become Ready:"
echo "  kubectl -n ${NAMESPACE} rollout status deployment/control-panel"
echo
echo "Access the web UI via NodePort (30180):"
echo "  http://<any-node-ip>:30180/"
echo
echo "Default admin username: admin"
echo "Login with the password you just set."
echo
echo "Manifests applied:"
echo "  - Namespace, ServiceAccount, ClusterRole, ClusterRoleBinding (rbac.yaml)"
echo "  - PersistentVolumeClaim control-panel-data (pvc.yaml)"
echo "  - Secret control-panel-secrets (secret.yaml, generated)"
echo "  - Deployment control-panel (deployment.yaml)"
echo "  - Service control-panel NodePort 30180 (service.yaml)"
